
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  resources:
    add-mappings: false
  security:
    user:
      name: ${AUTH_USER:user}
      password: ${AUTH_PASSWORD:password}

server:
  port: 9001

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    com.zaxxer.hikari: ERROR

elasticsearch:
  uri: ${ELASTICSEARCH_URI:http://127.0.0.1:9200}
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:changeme}

azure:
  account:
    name: ${AZURE_ACCOUNT_NAME}
    key: ${AZURE_ACCOUNT_KEY}
  storage:
    container: ${AZURE_STORAGE_CONTAINER}
    connection-string: "DefaultEndpointsProtocol=https;AccountName=${azure.account.name};AccountKey=${azure.account.key}"

