
spring:
  resources:
    add-mappings: false
  security:
    user:
      name: ${AUTH_USER:user}
      password: ${AUTH_PASSWORD:password}


server:
  port: 9001

elasticsearch:
  clusterName: ${ELASTICSEARCH_CLUSTER:local}
  host: ${ELASTICSEARCH_HOST:127.0.0.1}
  port: ${ELASTICSEARCH_PORT:9300}