
spring:
  resources:
    add-mappings: false
  security:
    user:
      name: user
      password: password

server:
  port: 9001

elasticsearch:
  clusterName: local
  host: 127.0.0.1
  port: 9200
