version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - run: ./gradlew build

  package:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/repo

    steps:
      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}
            - v1-dependencies-

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/app.tar | true

      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .

      - run:
          name: Save Docker image layer cache
          command: |
            docker save -o ~/app.tar app

      - save_cache:
          key: v1-dependencies-{{ .Branch }}
          paths:
            - ~/app.tar

workflows:
  version: 2
  build_and_package:
    jobs:
      - build
      - package:
          requires:
            - build
